name: travel
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.5.0
  flutter_dotenv: ^5.1.0
  provider: ^6.1.1
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  path: ^1.8.3
  uuid: ^4.4.0
  image_picker: ^1.1.2
  flutter_slidable: ^3.1.0
  supabase_auth_ui: ^0.5.4
  google_fonts: ^6.2.1
  path_provider: ^2.1.3
  shadcn_ui: ^0.24.0
  go_router: ^14.2.0
  equatable: ^2.0.5
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  logger: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  # Declare assets folder
  assets:
    - .env
    - assets/images/

  # To add custom fonts to your application, add a fonts section here, 