name: travel
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.3.4
  flutter_dotenv: ^5.1.0
  provider: ^6.1.1
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  path: ^1.8.3
  uuid: ^4.3.3
  image_picker: ^1.0.7
  flutter_slidable: ^3.0.1
  supabase_auth_ui: ^0.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env 