name: travel
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  google_sign_in: ^6.1.6
  provider: ^6.1.1
  flutter_riverpod: ^2.4.9
  logger: ^2.0.2+1
  uuid: ^4.2.2
  image: ^4.1.3
  flutter_image_compress: ^2.1.0
  cached_network_image: ^3.3.0
  photo_view: ^0.15.0
  http: ^1.1.2
  http_parser: ^4.0.2
  crypto: ^3.0.3
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.2.2
  path: ^1.8.3
  flutter_dotenv: ^5.1.0
  intl: any
  image_picker: ^1.1.2
  flutter_slidable: ^4.0.0
  google_fonts: ^6.2.1
  path_provider: ^2.1.3
  go_router: ^15.1.2
  equatable: ^2.0.5
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.0.0
  form_builder_validators: ^11.1.2
  flutter_form_builder: ^10.0.1
  eventflux: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  freezed: ^3.0.6
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - assets/images/
    - assets/images/auth/
    - assets/images/icons/
    - assets/icons/

  # To add custom fonts to your application, add a fonts section here, 