name: travel
description: A new Flutter project.
publish_to: 'none'
version: 0.1.5+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.1.0
  provider: ^6.1.1
  intl: any
  cached_network_image: ^3.3.1
  path: ^1.9.0
  uuid: ^4.4.0
  image_picker: ^1.1.2
  flutter_slidable: ^3.1.0
  google_fonts: ^6.2.1
  path_provider: ^2.1.3
  go_router: ^14.0.0
  equatable: ^2.0.5
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  logger: ^2.0.0
  freezed_annotation: ^2.4.1
  photo_view: ^0.15.0
  http: ^1.2.1
  flutter_form_builder: ^9.7.0
  form_builder_validators: ^11.1.2
  flutter_image_compress: ^2.1.0
  image: ^4.1.7
  google_sign_in: ^6.2.1

  # Firebase Dependencies
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  cloud_functions: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - assets/images/
    - assets/images/auth/
    - assets/images/icons/
    - assets/icons/

  # To add custom fonts to your application, add a fonts section here, 