// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRERzKYWUU8nzFiABYeNQO7dKoOuxx6vQ',
    appId: '1:213342165039:web:bd145392404471fd458eda',
    messagingSenderId: '213342165039',
    projectId: 'splitbase-7ec0f',
    authDomain: 'splitbase-7ec0f.firebaseapp.com',
    storageBucket: 'splitbase-7ec0f.firebasestorage.app',
    measurementId: 'G-BP4EW0YM44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVGuwcYI2oCHP3RCum0ayj-LUktArFBzY',
    appId: '1:213342165039:android:6caaed832566702b458eda',
    messagingSenderId: '213342165039',
    projectId: 'splitbase-7ec0f',
    storageBucket: 'splitbase-7ec0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0FnPasojdDi27FkwFX-zV4l34ipZ30YI',
    appId: '1:213342165039:ios:03e18acd08537cda458eda',
    messagingSenderId: '213342165039',
    projectId: 'splitbase-7ec0f',
    storageBucket: 'splitbase-7ec0f.appspot.com',
    iosBundleId: 'com.antonetti.travel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0FnPasojdDi27FkwFX-zV4l34ipZ30YI',
    appId: '1:213342165039:ios:772fdfeed7586f9e458eda',
    messagingSenderId: '213342165039',
    projectId: 'splitbase-7ec0f',
    storageBucket: 'splitbase-7ec0f.appspot.com',
    iosBundleId: 'com.example.travel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRERzKYWUU8nzFiABYeNQO7dKoOuxx6vQ',
    appId: '1:213342165039:web:a938a4e7812aaabb458eda',
    messagingSenderId: '213342165039',
    projectId: 'splitbase-7ec0f',
    authDomain: 'splitbase-7ec0f.firebaseapp.com',
    storageBucket: 'splitbase-7ec0f.appspot.com',
    measurementId: 'G-2YRXRS65BX',
  );
}
